package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQaSession;
import org.linlinjava.litemall.db.domain.LitemallQaSessionExample;

public interface LitemallQaSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    long countByExample(LitemallQaSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQaSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    int insert(LitemallQaSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQaSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    List<LitemallQaSession> selectByExample(LitemallQaSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQaSession record, @Param("example") LitemallQaSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQaSession record, @Param("example") LitemallQaSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(LitemallQaSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_session
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}