package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQaStatistics;
import org.linlinjava.litemall.db.domain.LitemallQaStatisticsExample;

public interface LitemallQaStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    long countByExample(LitemallQaStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQaStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    int insert(LitemallQaStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQaStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    List<LitemallQaStatistics> selectByExample(LitemallQaStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQaStatistics record, @Param("example") LitemallQaStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQaStatistics record, @Param("example") LitemallQaStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(LitemallQaStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qa_statistics
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}